import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

/*
 * Parse the CSV file to pass the data to Flight class row by row
 */
public class dataReader {
	/*
	 * Read the given CSV file generated by FlightWebScraping class
	 * and parse the data and convert to the appropriate variable format 
	 */
	public static ArrayList<Flight> readCSV(){
		ArrayList<Flight> flight = new ArrayList<Flight>();
		File flightData = new File ("");//TODO add the file name
		try {
			Scanner scan = new Scanner(flightData);
			scan.nextLine();//skip the first line
			while(scan.hasNextLine()) {
				String line = scan.nextLine();
				String [] dataLine = line.split("|");
				//parse each column in the line
				int flightPrice = Integer.parseInt(dataLine[1].substring(1)); //create a substring by removing the $ sign, data example: $1041
				String[] layover= dataLine[7].split("\\s+"); //split String ("2 stops (LAX, TPE)") by space in between
				int numberLayover = Integer.parseInt(layover[0]);//Only get the number of layover
				String flightDetail = dataLine[6];// data example: "Vancouver, BC, Canada - Vancouver Intl on 4/27 at 4:30 pm, lands in Beijing, China - Capital on 4/29 at 10:55 am"
				String duration = dataLine[9]; // data example: 27h 25m
				Flight flg = new Flight(flightPrice,numberLayover,flightDetail,duration);
				flight.add(flg);
			}
			scan.close();
		}catch(FileNotFoundException e) {
			System.out.println("Cannot open the file");
			
		}
		return flight;
	}
	
}
