import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

/**
 * Parse the CSV file to pass the data to Flight class row by row
 * 
 * @author issacwon
 *
 */
public class DataReader {
	/**
	 * Read the given CSV file generated by FlightWebScraping class and parse the
	 * data and convert to the appropriate variable format
	 * 
	 * @return ArrayList flight
	 */
	public ArrayList<Flights> readCSV() {
		ArrayList<Flights> flightList = new ArrayList<Flights>();
		File flightData = new File("ScrapedFlightData.txt");
		try {
			Scanner scan = new Scanner(flightData);
			while (scan.hasNextLine()) {
				String line = scan.nextLine();
				String[] dataLine = line.split("\\|");

				// if any of the columns is missing
				// skip the line
				if (dataLine.length < 21)
					break;

				int flightPrice = 0;
				if (!dataLine[1].isEmpty()) {
					flightPrice = Integer.parseInt(dataLine[1].replace("$", "").trim());
				} else
					break;

				String[] layover = dataLine[7].split(" ");

				// number of layover is preset to 0 for nonstop flights
				int numberLayover = 0;
				if (layover.length > 1) {
					numberLayover = Integer.parseInt(layover[0]);
				}
				String flightDetail = dataLine[20];
				String flightLink = dataLine[19];
				String flyNum = dataLine[4];
				Flights flight = new Flights(flightPrice, numberLayover, flightDetail, flyNum, flightLink);
				flightList.add(flight);

			}
			scan.close();
		} catch (FileNotFoundException e) {
			System.out.println("Cannot open the file");

		}
		return flightList;
	}

}
