import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

/**
 * Parse the CSV file to pass the data to Flight class row by row
 * @author issacwon
 *
 */
public class dataReader {
	/**
	 * Read the given CSV file generated by FlightWebScraping class
	 * and parse the data and convert to the appropriate variable format 
	 * @return ArrayList flight
	 */
	public static ArrayList<Flight> readCSV(){
		ArrayList<Flight> flightList = new ArrayList<Flight>();
		File flightData = new File ("scraped_temp.csv");//TODO add the file name
		try {
			Scanner scan = new Scanner(flightData);
			//scan.nextLine();//skip the first line
			while(scan.hasNextLine()) {
				String line = scan.nextLine();
				String[] dataLine = line.split("\\|");
				int flightPrice = Integer.parseInt(dataLine[2].replace("$","").trim());
				String[] layover = dataLine[8].split(" ");
				int numberLayover = Integer.parseInt(layover[0]);
				String flightDetail = dataLine[7];
				String duration = dataLine[10]; // data example: 27h 25m
				Flight flight = new Flight(flightPrice,numberLayover,flightDetail,duration);
				flightList.add(flight);
				
			}
			scan.close();
		}catch(FileNotFoundException e) {
			System.out.println("Cannot open the file");
			
		}
		return flightList;
	}
	
}
